export component MaxIcon inherits Rectangle {
    in property <color> line-color: white;
    in property <bool> is-maximized: false;

    width: 12px;
    height: 12px;

    Path {
        visible: !root.is-maximized;
        width: 100%;
        height: 100%;
        stroke: root.line-color;
        stroke-width: 1px;
        fill: transparent;
       
        MoveTo { x: 4; y: 4; }
        LineTo { x: 14; y: 4; }
        LineTo { x: 14; y: 14; }
        LineTo { x: 4; y: 14; }
        Close {}
    }

    Path {
        visible: root.is-maximized;

        width: 100%;
        height: 100%;
        stroke: root.line-color;
        stroke-width: 1px;
        fill: transparent;

        MoveTo { x: 4.5; y: 4.5; }
        LineTo { x: 13.5; y: 4.5; }
        LineTo { x: 13.5; y: 13.5; }
        LineTo { x: 4.5; y: 13.5; }
        Close {}

        MoveTo { x: 6.5; y: 2.5; }
        LineTo { x: 15.5; y: 2.5; }
        LineTo { x: 15.5; y: 11.5; } 
        
    }
}

export component MinIcon inherits Rectangle {
    in property <color> line-color: white;
    width: 20px;
    height: 20px;

    Path {
        viewbox-x: 0;
        viewbox-y: 0;
        viewbox-width:20;
        viewbox-height: 20;
        width: 100%;
        height: 100%;
        stroke: root.line-color;
        stroke-width: 1px;
        stroke_line_cap: round;
        
        MoveTo { x: 4; y: 9.5; }
        LineTo { x: 16; y: 9.5; }
    }
}

export component CloseIcon inherits Rectangle {
    width: 12px;
    height: 12px;
    in property <color> line-color: white;
    
    Path {
        width: 100%;
        height: 100%;
        stroke: root.line-color;
        stroke-width: 1px;
        stroke_line_cap: round;

        MoveTo { x: 2; y: 2; }
        LineTo { x: 10; y: 10; }
        
        MoveTo { x: 10; y: 2; }
        LineTo { x: 2; y: 10; }
    }
}