import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { MaxIcon ,MinIcon,CloseIcon} from "./icons.slint";
import { Theme } from "theme.slint";

export component TitleBar inherits Rectangle {
    in-out property <bool> is-maximized:false;
    in property <string> name:"Slint Application";
    in property <string> themetype:"light";
    height: 40px;
    background: Theme.active.background; 
    
    // 定义回调，让 C++ 处理窗口操作
    callback close();
    callback minimize();
    callback maximize();
       
    //主题切换
    Rectangle {
        x:parent.width - self.width * 4 ;
        y:0px;
        width: 52px;
        height:34px;
        background: theme_touch.pressed ? Theme.active.hover-bg : theme_touch.has-hover ? Theme.active.hover-bg : transparent;
        animate background { duration: 150ms; easing: ease-in-out; }
        theme_touch := TouchArea { clicked => { Theme.is_dark = !Theme.is_dark; } }
        Text {
                font-family: "bootstrap-icons";
                text: Theme.is_dark ? "\u{F1D2}":"\u{F496}";
                font-size:Theme.is_dark ? 16px:12px;
                color: Theme.active.text-color;
                horizontal-alignment:left;
                vertical-alignment: center;
            }
    }
    // 最小化
    Rectangle {
        x:parent.width - self.width * 3 ;
        y:0px;
        width: 52px;
        height:34px;
        background: min_touch.pressed ? Theme.active.hover-bg : min_touch.has-hover ? Theme.active.hover-bg : transparent;
        animate background { duration: 150ms; easing: ease-in-out; }
        min_touch := TouchArea { clicked => { root.minimize(); } }
        MinIcon{
            line-color: Theme.active.text-color;
        }
    }
    
        // 最大化
    Rectangle {
        x:parent.width - self.width * 2;
        y:0px;
        width: 52px;
        height:34px;
        background: max_touch.pressed ? Theme.active.hover-bg : max_touch.has-hover ? Theme.active.hover-bg : transparent;
        animate background { duration: 150ms; easing: ease-in-out; }
        max_touch := TouchArea { 

            clicked => { root.maximize();} 
        }
        MaxIcon{
            is-maximized: root.is-maximized;
            line-color: Theme.active.text-color;
        }
    }
    // 关闭
    Rectangle {
        x:parent.width - self.width;
        y:0px;
        width: 52px;
        height:34px;
        background: close_touch.pressed ? #e81123 : close_touch.has-hover ? #e23928 : transparent;
        animate background { duration: 150ms; easing: ease-in-out; }
        close-touch := TouchArea { clicked => { root.close(); } }
        CloseIcon{
            line-color: close_touch.has-hover ? white : Theme.active.text-color;
        }
       
    }
}